BEGIN;

CREATE TABLE COURSES(
  course_id  INTEGER PRIMARY KEY NOT NULL,
  course_num INTEGER NOT NULL,
  term_id    INTEGER NOT NULL,
  subject    TEXT NOT NULL);

CREATE TABLE SCRAPES(
  timestamp  DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  count      INTEGER NOT NULL,
  course     INTEGER NOT NULL,
  FOREIGN KEY(course) REFERENCES COURSES(course_id));

COMMIT;
